### ISSUE TITLE
Column vectors not rendered

### ISSUE THREAD

**Issue by ingodahn** [jsvine/nbpreview#3]
In the attached notebook, column vectors in the markdown cell don't render correctly in the online nbpreview. The notebook renders correct in CoCalc.
[Test.zip](https://github.com/jsvine/nbpreview/files/5759154/Test.zip)

Addition: Also the matrix expression
`\begin{pmatrix}
   a & b \\
   c & d
\end{pmatrix}`
which renders correctly in KaTex, doesn't render in nbpreview when used in a markdown cell.

**Comment by jsvine** [comment]
Thanks for opening this issue, @ingodahn. Could you share screenshots of how the notebook looks in CoCalc and how it appears for you in `nbpreview`?

**Comment by ingodahn** [comment]
Sure, attached is a zip NbTest.zip containing
* an updated version of the notebook
* a screenshot of its presentation in CoCalc
* the html of the notebook as exported from CoCalc
* a screenshot from the presentation by nbpreview as hosted on https://jsvine.github.io/nbpreview/

[NbTest.zip](https://github.com/jsvine/nbpreview/files/5763088/NbTest.zip)

**Comment by jsvine** [comment]
Many thanks, @ingodahn. This is quite helpful. In the developer console, after opening the notebook in `nbpreview`, there are a few KaTeX parse errors. I'll try to determine what's causing them.

**Comment by jsvine** [comment]
Thank you again for raising this issue, @ingodahn. I traced the problem back to the way that Markdown libraries (including `marked`, which is used here) treat backslashes (e.g., those in `\begin{pmatrix} a & b \\ c & d \end{pmatrix}`), which is as an escape character rather than a literal backslash. 

I figured out a way to get around this by *first* passing the Markdown through KaTeX's [auto-render extension](https://katex.org/docs/autorender.html) and then passing the result through `marked`. That tweak is now in `notebook.js` `v0.6.0` and reflected in this project as well. 

Here's what your test-notebook renders as now:

<img width="276" alt="Screen Shot 2021-01-09 at 3 59 50 PM" src="https://user-images.githubusercontent.com/534702/104108711-d2310f00-5294-11eb-8e45-e11d0f34c3ee.png">
